### ISSUE TITLE
Xiaomi MiWiFi 4

### ISSUE THREAD

**Issue by thanhvinh1** [lukasz1992/asuswrt-xiaomi#28]
Could I install this firmware to Xiaomi MiWiFi 4: https://wikidevi.wi-cat.ru/Xiaomi_MiWiFi_4
Specs like Mi WiFi Router 3G, the difference between r4 and r3g is to cast 128M memory and no USB port.
In case of it cannot install, could you please port this firmware to r4 device.
Thank you.

**Comment by thanhvinh1** [comment]
Here's some information I found:
https://openwrt.org/toh/hwdata/xiaomi/xiaomi_miwifi_r4
https://d13ht01.tk/engineering/20190601/hacking-mi-router-4/

**Comment by lukasz1992** [comment]
Flash mapping is diffrent, and because of that, firmwares are theoretically not compatible.

You could now try to flash 3G firmware (which will destroy obr partition), but firmware should work, as kernel partitions remain the same.

I have an idea for patch, to do not use last 28MB of flash, which will keep obr untouched, but:
1. I need some time to do it
2. I have no hardware to test it, I need tester.

**Comment by lukasz1992** [comment]
@thanhvinh1 Please backup obr partition (if you could send me it, I will check if is there something important here. You can flash current firmware and become a tester, it should boot and work.

Do you have gpio definitions and DTS for this device?

**Comment by lukasz1992** [comment]
@thanhvinh1 Update:
LAN/WAN mappings are diffrent, probably GPIO too.
Without hardware or dotation I can not test firmwares.

Current version will not work on this device (you can try if you want, but I doubt it works)

**Comment by lukasz1992** [comment]
I could not find any details about GPIO and network mappings.
Do you have this device or could provide me these informations? I am able to introduce support to it.
