### ISSUE TITLE
App detection and Adaptive QoS not working

### ISSUE THREAD

**Issue by guga082011** [lukasz1992/asuswrt-xiaomi#41]
Traffic analayzer apps usage not showing properly, only showing general apps usage
![Anotação 2020-06-29 160913](https://user-images.githubusercontent.com/59765082/86046072-f62cb180-ba22-11ea-81b3-9a7bdd83a558.png)

**Comment by lukasz1992** [comment]
Yes, I see the same problem on my router. Probably it was broken in 89d0169d.

My first priority is delete crap, described here: http://www.weatherimagery.com/blog/asus_trendmicro_data_collection/
Then I will try to fix things.
I still have some work pending:
- if you accept TM license, it seems that some settings are ignored (you can disable Traffic Analyzer, but it still works)
- some binaries still have hardcoded addresses (described above)

Instead of repairing Apps, I am going to hide not working options.

**Comment by lukasz1992** [comment]
Problem fixed in b9618b0a, I still need to test it internally.
