### ISSUE TITLE
How is it better / different than OpenWRT? 

### ISSUE THREAD

**Issue by xcom169** [lukasz1992/asuswrt-xiaomi#63]
How is it better / different than OpenWRT?  

Can it support something which is not supported in OpenWRT ?

**Comment by lukasz1992** [comment]
It depends what you need.

AsusWRT:
+ Stable board support
+ Stable wireless drivers (not mt76 garbage)
+ Simpler web interface (no need console or ugly LuCI to do everything)
+ Fast NTFS/HFS+ driver (instead of slower fuse)

OpenWRT:
+ Recent kernel, built-in drivers for many hardware
+ Almost no closed-source things (with one exception of mt76)
+ Easier to customize (you can implement scripts and install apps in AsusWRT, but OpenWRT makes it easier)

**Comment by xcom169** [comment]
Can you please post to the Github page, how can one 'MTD' it to MIR3G , OpenWRT device? 
Your .trx file also contains a bootloader, or that is totally separate ?
